
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentProcessing.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class AffairsNomenclature
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AffairsNomenclature()
    {

        this.Documents = new HashSet<Document>();

    }


    public int Id { get; set; }

    public string IndexOfCase { get; set; }

    public string SectionName { get; set; }

    public string Headline { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Document> Documents { get; set; }

}

}
