
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DocumentProcessing.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Document
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Path { get; set; }

    public int CreatorId { get; set; }

    public string CreationDate { get; set; }

    public int TypeId { get; set; }

    public string DocIndex { get; set; }

    public string ExecutionPeriod { get; set; }

    public string RegistrationDate { get; set; }

    public string DocHeader { get; set; }

    public Nullable<int> ManagerId { get; set; }

    public string Resolution { get; set; }

    public Nullable<int> ExecutorId { get; set; }

    public string ExecutorNote { get; set; }

    public Nullable<int> ControllerId { get; set; }

    public string ControllerNote { get; set; }

    public int NomenclatureId { get; set; }



    public virtual AffairsNomenclature AffairsNomenclature { get; set; }

    public virtual User Inspector { get; set; }

    public virtual User Creator { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual User Executor { get; set; }

    public virtual User Manager { get; set; }

}

}
